### ISSUE TITLE
Updating the project for sepolia

### ISSUE THREAD

**Issue by Amanb1145** [dapplets/swarm-uploader#1]
Hey,
I came across this amazing project today and I want to calculate `bzz stamps `for my project but I am using `sepolia` as testnet so can you help me how can I make it work for `sepolia` ?
I tried-
`const provider = new ethers.providers.JsonRpcProvider('https://rpc.ankr.com/eth_sepolia', 11155111);
` const contract = new ethers.Contract('0x621e455c4a139f5c4e4a8122ce55dc21630769e4', abi, provider);
`
and got this error on console-
```
index.ts:261 Uncaught (in promise) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="lastPrice()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.0)
    at Logger.makeError (index.ts:261:1)
    at Logger.throwError (index.ts:273:1)
    at Interface.decodeFunctionResult (interface.ts:423:1)
    at Contract.<anonymous> (index.ts:400:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:1:1)
```
and response of api call to `https://rpc.ankr.com/eth_sepolia0000`
payload- 
`{"method":"eth_call","params":[{"to":"0x621e455c4a139f5c4e4a8122ce55dc21630769e4","data":"0x053f14da"},"latest"],"id":43,"jsonrpc":"2.0"}`
response- 
`{"jsonrpc":"2.0","id":43,"result":"0x"}`

Thanks

**Comment by alsakhaev** [comment]
Hello, Aman!

As I know, Swarm is just preparing to migrate to Sepolia, and now works in Goerli (testnet) and Gnosis Chain (mainnet) networks only. We need to wait for them to deploy smart contracts "PostageStamp" to the Sepolia network. https://blog.ethswarm.org/foundation/2023/swarm-community-call-25-may-recap/

You received the error "call revert exception", because in Sepolia no contract exist with address "0x621e455c4a139f5c4e4a8122ce55dc21630769e4" https://sepolia.etherscan.io/address/0x621e455c4a139f5c4e4a8122ce55dc21630769e4

If you're interested in calculating of required bzz stamps amount for a given file size and lifetime, you can check this code also:
https://github.com/dapplets/media-downloader/blob/62c7a01f961de8f7916668bc41237d61acf9c3dd/dapplet-youtube/src/api.ts#L67-L103

I'm not sure that this dapplet works, because YouTube changes their protection algorithms, but I have a product video, where you can see how it works. The user experience that we received is not so good, because you have to wait for the propagation of postage stamps in the Swarm network, before the stamps can be used. It can take a couple of minutes. https://drive.google.com/file/d/1X2ABYg5wJOgMizRMI7s7OcFGxc0I2IMH/view?usp=sharing

**Comment by Amanb1145** [comment]
Thanks @alsakhaev for this information :)
